import { Project } from "@/models/project";

export const PROJECTS: Project[] = [
  {
    title: "AI Report Generator @ Klinik Pintar",
    slug: "ai-report-generator-klinik-pintar",
    description:
      "AI-driven report generator web app for Klinik Pintar using Next.js with a Retrieval-Augmented Generation (RAG) technique, enabling faster and more accurate report insights.",
    techStack: ["NextJS", "TailwindCSS", "PostgreSQL", "Docker", "OpenAI SDK"],
    year: "2025",
    github: "https://github.com/klinikpintar/ai-report-generator",
    demo: "https://ai-report-generator-staging.up.railway.app",
    role: "Scrum Master & Fullstack Developer",
    images: [
      {
        type: "image",
        src: "/assets/images/ai-report-generator/1.png",
        height: 1080,
        width: 1960,
        alt: "Chat Room AI Report Generator",
      },
      {
        type: "video",
        src: "/assets/images/ai-report-generator/2.mp4",
        height: 1080,
        width: 1960,
        alt: "Walkthrough Chat to Export",
      },
      {
        type: "image",
        src: "/assets/images/ai-report-generator/3.png",
        height: 1080,
        width: 1960,
        alt: "Landing Page Admin",
      },
      {
        type: "image",
        src: "/assets/images/ai-report-generator/4.png",
        height: 1080,
        width: 1960,
        alt: "AI Config Admin",
      },
      {
        type: "image",
        src: "/assets/images/ai-report-generator/5.png",
        height: 1080,
        width: 1960,
        alt: "User Management Page Admin",
      },
    ],
  },
  {
    title: "Al Utsmani Website",
    slug: "alutsmani",
    description:
      "Revamped the company profile website for Yayasan Al Utsmani with features like blog, program registration, and automated donations via payment gateway. Built an admin app to manage users, content, and certificates, streamlining workflows and improving service.",
    techStack: ["Next.js", "Django", "Celery", "PostgreSQL", "Firebase"],
    year: "2024",
    demo: "https://dev.alutsmani.com/",
    role: "Vice Lead Developer",
    images: [
      {
        type: "image",
        src: "/assets/images/utsmani/1.png",
        height: 1080,
        width: 1960,
        alt: "Landing Page Utsmani",
      },
      {
        type: "image",
        src: "/assets/images/utsmani/2.png",
        height: 1080,
        width: 1960,
        alt: "List of Program Education Page Utsmani",
      },
      {
        type: "video",
        src: "/assets/images/utsmani/3.mkv",
        height: 1080,
        width: 1960,
        alt: "Program Education Registration Page Utsmani",
      },
      {
        type: "image",
        src: "/assets/images/utsmani/4.png",
        height: 1080,
        width: 1960,
        alt: "Admin View Utsmani",
      },
    ],
  },
  {
    title: "Tautin",
    slug: "tautin",
    description:
      "Link shortener with fully customizable URLs. Simplify your long links in the easiest way.",
    techStack: ["NestJS", "NextJS", "TailwindCSS", "PostgreSQL"],
    year: "2024",
    demo: "https://tautin.link/",
    github: "https://github.com/ilhamelhamdi/tautin",
    role: "Fullstack Developer",
    images: [
      {
        type: "image",
        src: "/assets/images/tautin-1.png",
        height: 1080,
        width: 1080,
        alt: "Tautin",
      },
    ],
  },
  // {
  //   title: "Fashionpedia",
  //   slug: "fashionpedia",
  //   description:
  //     "A marketplace for those who love selling and buying thrifted clothes. This is the first project that implemented microservice style architecture. I built a service for managing listing and order.",
  //   techStack: ["SpringBoot", "PostgreSQL", "HTML", "CSS", "Javascript"],
  //   year: "2024",
  //   demo: "https://fashionpedia.my.id/",
  //   github: "https://github.com/Fashionpedia-A2",
  //   role: "Fullstack Developer",
  //   collaborator: [
  //     { name: "Fredo", github: "https://github.com/Frmeta" },
  //     { name: "Nabil", github: "https://github.com/Nabilcodes" },
  //     { name: "Rafi", github: "https://github.com/RafGhan" },
  //     { name: "Sefriano", github: "https://github.com/riorio805" },
  //   ],
  //   images: [
  //     {
  //       type: "image",
  //       src: "/assets/images/tautin-1.png",
  //       height: 1080,
  //       width: 1080,
  //       alt: "Fashionpedia",
  //     },
  //   ],
  // },
  {
    title: "Bukoo",
    slug: "bukoo",
    description: "A website for sharing and discussing all about books.",
    techStack: ["Django", "HTML", "CSS", "JavaScript"],
    year: "2023",
    github: "https://github.com/B03-PBP-2023/bukoo",
    demo: "https://bukoo-production.up.railway.app/",
    role: "Fullstack Developer",
    collaborator: [
      { name: "Sekar", github: "https://github.com/arumasekar" },
      { name: "Fayya", github: "https://github.com/fayyazheva" },
      { name: "Asadilhaq", github: "https://github.com/FBK15" },
      { name: "Muzaki", github: "https://github.com/muzakiahmdz" },
    ],
    images: [
      {
        type: "image",
        src: "/assets/images/bukoo/1-landing-page.png",
        height: 1080,
        width: 1080,
        alt: "Bukoo",
      },
      {
        type: "image",
        src: "/assets/images/bukoo/2-book-detail.png",
        height: 1080,
        width: 1080,
        alt: "Bukoo",
      },
    ],
  },
  {
    title: "BETIS 2023 Website",
    slug: "betis-2023-website",
    description:
      "A website providing free guidance services for prospective students to prepare for university admission. In this project, I took on the role of Frontend Developer to build the About page.",
    techStack: ["NextJS", "TailwindCSS"],
    demo: "https://betis2023.vercel.app/",
    github: "https://github.com/BETIS-Fasilkom-UI/BETIS23-FE",
    role: "Frontend Developer",
    year: "2023",
    images: [
      {
        type: "image",
        src: "/assets/images/betis-2023/1-landing-page.png",
        height: 1080,
        width: 1920,
        alt: "BETIS Fasilkom UI 2023's Website",
      },
      {
        type: "video",
        src: "/assets/images/betis-2023/2-about-page.mp4",
        height: 1080,
        width: 1920,
        alt: "BETIS Fasilkom UI 2023's Website",
      },
    ],
  },
  {
    title: "Bukoo Mobile",
    slug: "bukoo-mobile",
    description: "A mobile version of the book community platform, Bukoo.",
    techStack: ["Flutter"],
    year: "2023",
    github: "https://github.com/B03-PBP-2023/bukoo-mobile",
    demo: "https://install.appcenter.ms/orgs/bukoo/apps/bukoo/distribution_groups/public",
    role: "Frontend Developer",
    collaborator: [
      { name: "Sekar", github: "https://github.com/arumasekar" },
      { name: "Fayya", github: "https://github.com/fayyazheva" },
      { name: "Asadilhaq", github: "https://github.com/FBK15" },
      { name: "Muzaki", github: "https://github.com/muzakiahmdz" },
    ],
    images: [
      {
        type: "image",
        src: "/assets/images/bukoo-mobile/4.jpg",
        height: 1080,
        width: 1080,
        alt: "Bukoo Mobile's mockup",
      },
      {
        type: "video",
        src: "/assets/images/bukoo-mobile/1.mp4",
        height: 1080,
        width: 1080,
        alt: "Bukoo Mobile's home page",
      },
      {
        type: "video",
        src: "/assets/images/bukoo-mobile/2.mp4",
        height: 1080,
        width: 1080,
        alt: "Bukoo Mobile's book detail page",
      },
      {
        type: "video",
        src: "/assets/images/bukoo-mobile/3.mp4",
        height: 1080,
        width: 1080,
        alt: "Bukoo Mobile's discussion forum page",
      },
    ],
  },
  // {
  //   title: "Satset MOOC",
  //   slug: "satset-mooc",
  //   description:
  //     "An open online course website. Create your own courses with lectures and interactive quizzes as Instructor. Enroll verified courses and take lectures and quizzes as a Student.This project is a final project collaboration at Software Engineering Academy COMPFEST 14. I took part in the Frontend side.",
  //   techStack: ["ReactJS", "TailwindCSS"],
  //   year: "2022",
  //   demo: "https://satset-mooc.vercel.app/",
  //   github: "https://github.com/ilhamelhamdi/frontend-satset",
  //   role: "Frontend Developer",
  //   collaborator: [
  //     { name: "Fathoni", github: "https://github.com/githubnyathoni" },
  //     { name: "Evan", github: "https://github.com/evan-aurelrius" },
  //     { name: "Adnan", github: "https://github.com/alfa000" },
  //   ],
  //   images: [
  //     {
  //       type: "image",
  //       src: "/assets/images/tautin-1.png",
  //       height: 1080,
  //       width: 1080,
  //       alt: "Satset MOOC",
  //     },
  //     {
  //       type: "image",
  //       src: "/assets/images/tautin-1.png",
  //       height: 1080,
  //       width: 1080,
  //       alt: "Satset MOOC",
  //     },
  //   ],
  // },
];
